
from enum import Enum

class Model(Enum):
	EXP = 1
	POW = 2
	WEI = 3

#################
## Model Frame ##
#################

EXP_DEFAULT_NUMBER_OF_SEGMENTS = 2
EXP_MAX_NUMBER_OF_SEGMENTS = 5

POW_DEFAULT_PROXIMAL_LIMIT = 1.0
POW_DEFAULT_DISTAL_LIMIT = 300

WEI_DEFAULT_NUMBER_OF_RUNS = 20
WEI_DEFAULT_ITERATIONS_PER_RUN = 1000
WEI_DEFAULT_LAMBDA_LOWER_BOUND = 0.0
WEI_DEFAULT_LAMBDA_UPPER_BOUND = 1000
WEI_DEFAULT_K_LOWER_BOUND = 0.0
WEI_DEFAULT_K_UPPER_BOUND = 2.0